ACCOUNTS = [
     "011: Zřizovací výdaje",
                    "012: Nehmotné výsledky výzkumu a vývoje",
                    "013: Software",
                    "014: Ocenitelná práva",
                    "015: Goodwill",
                    "019: Ostatní dlouhodobý nehmotný majetek",
                    "021: Stavby",
                    "022: Hmotné movité věci a jejich soubory",
                    "025: Pěstitelské celky trvalých porostů",
                    "026: Základní stádo a tažná zvířata",
                    "029: Ostatní dlouhodobý hmotný majetek",
                    "031: Pozemky",
                    "032: Umělecká díla a sbírky",
                    "041: Pořízení dlouhodobého nehmotného majetku",
                    "042: Pořízení dlouhodobného hmotného majetku",
                    "043: Pořízení dlouhodobého finančního majetku",
                    "051: Poskytnuté zálohy na dlouhodobný nehmotný majetek",
                    "052: Poskytnuté zálohy na dlouhodobý hmotný majetek",
                    "053: Poskytnuté zálohy na dlouhodobý finanční majetek",
                    "061: Podíly v ovládaných a řízených osobách",
                    "062: Podíly v účetních jednotkách pod podstatným vlivem",
                    "063: Ostatní cenné papíry a podíly",
                    "065: Dluhové cenné papíry držené do splatnosti",
                    "066: Půjčky a úvěry - ovládající a řídící osoba, podst.",
                    "067: Ostatní půjčky",
                    "069: Jiný dlouhodobý finanční majetek",
                    "071: Oprávky ke zřizovacím výdajům",
                    "072: Oprávky k nehm. výsledkům výzkumu a vývoje",
                    "073: Oprávky k softwaru",
                    "074: Oprávky k ocenitelným právům",
                    "075: Oprávky k goodwillu",
                    "079: Oprávky k ostatnímu dlouhodobému nehm. majetku",
                    "081: Oprávky ke stavbám",
                    "082: Oprávky k sam. mov. věcem a souborům mov. věcí",
                    "085: Oprávky k pěstitelským celkům trvalých porostů",
                    "086: Oprávky k základnímu stádu a tažným zvířatům",
                    "089: Oprávky k ostatnímu dlouhodobému hmotnému majetku",
                    "091: Opravná položka k dlouhodobému nehm. majetku",
                    "092: Opravná položka k dlouhodobému hmotnému majetku",
                    "093: Opravná položka k dl. nedokončenému nehm. majetku",
                    "094: Opravná položka k dl. nedokončenému hmot. majetku",
                    "095: Opravná položka k poskyt. zálohám na dl. majetek",
                    "096: Opravná položka k dlouhodobému finančnímu majetku",
                    "097: Oceňovací rozdíl k nabytému majetku",
                    "098: Oprávky k oceňovacímu rozdílu k nabytému majetku",
                    "111: Pořízení materiálu",
                    "112: Materiál na skladě",
                    "119: Materiál na cestě",
                    "121: Nedokončená výroba",
                    "122: Polotovary vlastní výroby",
                    "123: Výrobky",
                    "124: Zvířata",
                    "131: Pořízení zboží",
                    "132: Zboží na skladě a v prodejnách",
                    "139: Zboží na cestě",
                    "151: Poskytnuté zálohy na materiál",
                    "152: Poskytnuté zálohy na zvířata",
                    "153: Poskytnuté zálohy na zboží",
                    "191: Opravná položka k materiálu",
                    "192: Opravná položka k nedokončené výrobě",
                    "193: Opravná položka k polotovarům vl. výroby",
                    "194: Opravná položka k výrobkům",
                    "195: Opravná položka ke zvířatům",
                    "196: Opravná položka ke zboží",
                    "197: Opravná položka k poskyt. zálohám na materiál",
                    "198: Opravná položka k poskyt. zálohám na zvířata",
                    "199: Opravná položka k poskyt. zálohám na zboží",
                    "211: Pokladna",
                    "213: Ceniny",
                    "221: Bankovní účty",
                    "231: Krátkodobé bankovní úvěry",
                    "232: Eskontní úvěry",
                    "241: Emitované krátkodobé dluhopisy",
                    "249: Ostatní krátkodobé finanční výpomoci",
                    "251: Majetkové cenné papíry k obchodování",
                    "252: Vlastní akcie a vlastní obchodní podíly",
                    "253: Dluhové cenné papíry k obchodování",
                    "255: Vlastní dluhopisy",
                    "256: Dluhové CP se splat. do 1 roku drž. do splatnosti",
                    "257: Ostatní cenné papíry k obchodování",
                    "259: Pořizovaný krátkodobý finanční majetek",
                    "261: Peníze na cestě",
                    "291: Opravná položka ke krátk. finančnímu majetku",
                    "311: Odběratelé",
                    "312: Směnky k inkasu",
                    "313: Pohledávky za eskontované cenné papíry",
                    "314: Poskytnuté provozní zálohy - dlouhodobé i krátkod.",
                    "315: Ostatní pohledávky",
                    "321: Dodavatelé",
                    "322: Směnky k úhradě",
                    "324: Přijaté provozní zálohy",
                    "325: Ostatní závazky",
                    "331: Zaměstnanci",
                    "333: Ostatní závazky k zaměstnancům",
                    "335: Pohledávky za zaměstnanci",
                    "336: Zúčtování s instutucemi soc. zabezp. a zdr. pojišť",
                    "341: Daň z příjmů",
                    "342: Ostatní přímé daně",
                    "343: Daň z přidané hodnoty",
                    "345: Ostatní daně a poplatky",
                    "346: Dotace ze státního rozpočtu",
                    "347: Ostatní dotace",
                    "349: Spojovací účet k DPH (dodání v rámci EU)",
                    "351: Pohledávky - ovládající a řídící osoba",
                    "352: Pohledávky - podstatný vliv",
                    "353: Pohledávky za upsaný vlastní kapitál",
                    "354: Pohledávky za společníky při úhradě ztráty",
                    "355: Ostatní pohledávky za společníky a členy družstva",
                    "358: Pohledávky za účastníky sdružení",
                    "361: Závazky - ovládající a řídící osoba",
                    "362: Závazky - podstatný vliv",
                    "364: Závazky ke společníkům při rozdělování zisku",
                    "365: Ostatní závazky ke společníkům a členům družstva",
                    "366: Závazky ke společníkům a čl. družstva ze záv. činn",
                    "367: Závazky z upsaných nespl. cenných papírů a vkladů",
                    "368: Závazky k účastníkům sdružení",
                    "371: Pohledávky z prodeje podniku",
                    "372: Závazky z koupě podniku",
                    "373: Pohledávky a závazky z pevných termín. operací",
                    "374: Pohledávky z pronájmu",
                    "375: Pohledávky z emitovaných dluhopisů",
                    "376: Nakoupené opce",
                    "377: Prodané opce",
                    "378: Jiné pohledávky",
                    "379: Jiné závazky",
                    "381: Náklady příštích období",
                    "382: Komplexní náklady příštích období",
                    "383: Výdaje příštích období",
                    "384: Výnosy příštích období",
                    "385: Příjmy příštích období",
                    "388: Dohadné účty aktivní",
                    "389: Dohadné účty pasívní",
                    "391: Opravná položka k pohledávkám",
                    "395: Vnitřní zúčtování",
                    "398: Spojovací účet při sdružení",
                    "411: Základní kapitál",
                    "412: Emisní ážio",
                    "413: Ostatní kapitálové fondy",
                    "414: Oceňovací rozdíly z přecenění majetku a závazků",
                    "418: Oceňovací rozdíly z přecenění při přeměnách",
                    "419: Změny základního kapitálu",
                    "421: Zákonný rezervní fond",
                    "422: Nedělitelný fond",
                    "423: Statutární fondy",
                    "427: Ostatní fondy",
                    "428: Neuhrazený zisk minulých let",
                    "429: Neuhrazená ztráta minulých let",
                    "431: Hospodářský výsledek ve schovalovacím řízení",
                    "451: Zákonné rezervy",
                    "455: Rezerva na daň z příjmů",
                    "459: Ostatní rezervy",
                    "461: Dlouhodobé bankovní úvěry",
                    "471: Dlouhodobé závazky - ovládající a řídící osoba",
                    "472: Dlouhodobé závazky - podstatný vliv",
                    "473: Emitované dluhopisy",
                    "474: Závazky z pronájmu",
                    "475: Dlouhodobé přijaté zálohy",
                    "478: Dlouhodobé směnky k úhradě",
                    "479: Jiné dlouhodobé závazky",
                    "481: Odložený daňový závazek a pohledávka",
                    "491: Účet individuálního podnikatele",
                    "501: Spotřeba materiálu",
                    "502: Spotřeba energie",
                    "503: Spotřeba ostatních neskladovatelných dodávek",
                    "504: Prodané zboží",
                    "511: Opravy a udržování",
                    "512: Cestovné",
                    "513: Náklady na reprezentaci",
                    "518: Ostatní služby",
                    "521: Mzdové náklady",
                    "522: Příjmy společníků a čl. družstva ze závis.činnosti",
                    "523: Odměny členům orgánů společností a družstva",
                    "524: Zákonné sociální pojištění",
                    "525: Ostatní sociální pojištění",
                    "526: Sociální náklady individuálního podnikatele",
                    "527: Zákonné sociální náklady",
                    "528: Ostatní sociální náklady",
                    "531: Daň silniční",
                    "532: Daň z nemovitostí",
                    "538: Ostatní daně a poplatky",
                    "541: Zůstatková cena prodaného",
                    "542: Prodaný materiál",
                    "543: Dary",
                    "544: Smluvní pokuty a úroky z prodlení",
                    "545: Ostatní pokuty a penále",
                    "546: Odpis pohledávky",
                    "548: Ostatní provozní náklady",
                    "549: Manka a škody",
                    "551: Odpisy dlouhodobého nehmotného a hmotného majetku",
                    "552: Tvorba a zúčtování zákonných rezerv",
                    "554: Tvorba a zúčtování ostatních rezerv",
                    "555: Tvorba a zúčtování kompl. nákladů příštích období",
                    "557: Tvorba a zúčtování opr. pol. k opr. pol. k nab.maj",
                    "558: Tvorba a zúčtování zákonných opravných položek",
                    "559: Zúčtování opravných položek",
                    "561: Prodané cenné papíry a podíly",
                    "562: Úroky",
                    "563: Kurzové ztráty",
                    "564: Náklady z přecenění cenných papírů",
                    "566: Náklady z finančního majetku",
                    "567: Náklady z derivátových operací",
                    "568: Ostatní finanční náklady",
                    "569: Manka a škody na finančním majetku",
                    "574: Tvorba a zúčtování finančních rezerv",
                    "579: Trorba a zúčtování opr. položek ve fin. činnosti",
                    "581: Náklady na změnu metody",
                    "582: Škody",
                    "583: Změna stavu výrobků",
                    "584: Tvorba a zúčtování rezerv",
                    "585: Aktivace materiálu a zboží",
                    "587: Aktivace dlouhodobého nehmotného majetku (od 2016)",
                    "588: Aktivace dlouhodobého hmotného majetku (od 2016)",
                    "589: Tvorba a zúčtování opravných položek",
                    "591: Daň z příjmů z běžné činnosti - splatná",
                    "592: Daň z příjmů z běžné činnosti - odložená",
                    "593: Daň z příjmů z mimoř. činnosti - splatná",
                    "594: Daň z příjmů z mimoř. činnosti - odložená",
                    "595: Dodatečné odvody daně z příjmů",
                    "596: Převod podílu na výsl. hospodaření společníkům",
                    "597: Převod provozních nákladů",
                    "598: Převod finančních nákladů",
                    "601: Tržby za vlastní výrobky",
                    "602: Tržby z prodeje služeb",
                    "604: Tržby za zboží",
                    "611: Změna stavu nedokončené výroby",
                    "612: Změna stavu polotovarů",
                    "613: Změna stavu výrobků",
                    "614: Změna stavu zvířat",
                    "621: Aktivace materiálu a zboží",
                    "622: Aktivace vnitropodnikových služeb",
                    "623: Aktivace dlouhodobého nehm. majetku",
                    "624: Aktivace dlouhodobého hmotného majetku",
                    "641: Tržby z prodeje DNaHM",
                    "642: Tržby z prodeje materiálu",
                    "644: Smluvní pokuty a úroky z prodlení",
                    "646: Výnosy z odepsaných pohledávek",
                    "648: Ostatní provozní výnosy",
                    "661: Tržby z prodeje cenných papírů a podílů",
                    "662: Úroky",
                    "663: Kurzové zisky",
                    "664: Výnosy z přecenění cenných papírů",
                    "665: Výnosy z dlouhodobého finančního majetku",
                    "666: Výnosy z krátkodobého finančního majetku",
                    "667: Výnosy z derivátových operací",
                    "668: Ostatní finanční výnosy",
                    "681: Výnosy ze změny metody",
                    "688: Ostatní mimořádné výnosy",
                    "697: Převod provozních výnosů",
                    "698: Převod finančních výnosů",
                    "701: Počáteční účet rozvažný",
                    "702: Konečný účet rozvažný",
                    "710: Účet zisků a ztrát",]
